house/account/urls.py
from django.urls import path
from knox import views as knox_views
from django.contrib.auth.views import LogoutView
from django.conf.urls import url
from account.views import (register_page, phone_validation,
                           otp_validator, login_page, set_password,
                           registeration, LoginView, passwordrecovery_page,
                           change_password, phone_validation_passchange,
                           new_password_replace, dashboard_page, userinfo, edituserinfo, bookmark, bookmarkdisplay, getuserbookmark
                           )


urlpatterns = [
    path('bookmark-display/', bookmarkdisplay, name='bookmarkdisplay'),
    path('bookmark-house/', bookmark, name='bookmark'),
    path('user-bookmark/', getuserbookmark, name='getuserbookmark'),
    path('dashboard/', dashboard_page, name='dashboard_page'),
    path('userinformations/', userinfo, name='userinfo'),
    path('edit/', edituserinfo, name='edituserinfo'),
    path('new_password_replace/', new_password_replace,
         name='new_password_replace'),
    path('phone_validation_pass/', phone_validation_passchange,
         name='phone_validation_passchange'),
    path('password_change/', change_password, name='change_password'),
    path('password-recovery/', passwordrecovery_page,
         name='passwordrecovery_page'),
    path('registration/', register_page, name='register_page'),
    path('user_registeration/', registeration, name='registeration'),
    path('password/', set_password, name='set_password'),
    path('loginuser/', login_page, name='login_page'),
    path('validation_number/', phone_validation, name='phone_validation'),
    path('validation_otp/', otp_validator, name='otp_validator'),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('logout_user/', LogoutView.as_view(), name='logout'),
]

house/base/urls.py
from django.urls import path

from .views import homepage, Ads, detail, housedetail

urlpatterns = [
    path('', homepage, name='homepage'),
    path('getads/', Ads.as_view(), name='Ads'),
    path('housedetails/', housedetail, name='housedetail'),
    path('housedetail/<int:id>/', detail, name='detail'),
    
]

house/house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('', include(('account.urls', 'account'), namespace='account')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

house/account/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _


class MyUserManager(BaseUserManager):
    def create_user(self, phone, password, **extra_fields):

        if not phone:
            raise ValueError('Users must have an phone number.')
        if not password:
            raise ValueError('Users must have an password.')

        user = self.model(phone=phone, **extra_fields)

        user.set_password(password)
        
        user.save()
        return user

    

    def create_superuser(self, phone, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(phone, password, **extra_fields)


class User(AbstractUser):
    username = None
    phone_regex = RegexValidator(
        regex=r'(\+98|0)?9\d{9}',
        message="phone number mustbe entered in the format:'+99999999'. up tho 14 digits allowed.")
    phone = models.CharField(validators=[phone_regex], max_length=15, unique=True)
    
    objects = MyUserManager()

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.phone

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    

class OtpNumber(models.Model):
    phonenumber = models.CharField(max_length=25, null=True)
    otp_number = models.CharField(max_length=25, null=True)
    counts = models.PositiveIntegerField(default=0, null=True, blank=True)
    validate = models.BooleanField(default=False)

    def __str__(self):
        return self.phonenumber

house/account/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth.decorators import login_required
from .models import User, OtpNumber
import random
from kavenegar import *
from .serializer import CreateUserSerializer, LoginSerializer, UserSerializer, bookmarkserializer
from knox.views import LoginView as KnoxLoginView
from knox.models import AuthToken
from django.contrib.auth import login
import re
from base.models import Bookmark

reg = "^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$"
match_re = re.compile(reg)


def register_page(request):  # registeration page.
    return render(request, 'registreation.html')


def passwordrecovery_page(request):  # password recovery page.
    return render(request, 'passwordrecovery.html')


def login_page(request):  # login user page.
    return render(request, 'login.html')


def set_password(request):  # set password page.
    return render(request, 'set_password.html')


def new_password_replace(request):  # set new password.
    return render(request, 'new_password_replace.html')


@login_required(login_url='/loginuser/')
@permission_classes([IsAuthenticated])
def dashboard_page(request):  # user panel page.
    return render(request, 'dashboard.html')


@ api_view(['POST'])
@permission_classes([AllowAny])
def phone_validation(request):  # send otp code to phonenumber.
    phonenumber = request.POST.get('phonenumber')
    if phonenumber:
        user = User.objects.filter(phone__iexact=phonenumber)
        if user.exists():
            return Response({
                'status': False,
                'detail': 'این شماره تلفن قبلا در سایت ثبت نام شده است.'
            })
        else:
            key = send_otp(phonenumber)
            if key:
                obj = OtpNumber.objects.filter(phonenumber=phonenumber)
                if obj:
                    objcount = obj.first()
                    if objcount.counts < 7:
                        # api = KavenegarAPI(
                        #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                        # params = {
                        #     'receptor': phonenumber,
                        #     'token': key,
                        #     'template': 'Verify',
                        #     'message': 'Kaveh specialized Web service '
                        # }
                        # response = api.verify_lookup(params)
                        objcount.counts += 1
                        objcount.otp_number = key
                        objcount.save()
                        return Response({
                            'status': True,
                            'detail':
                            'کد تایید ارسال شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail':
                            'تعداد درخواست های تایید هویت پیامکی بیش از حد مجاز است لطفا با بخش پشتیبانی تماس فرمایید.'
                        })
                else:
                    # api = KavenegarAPI(
                    #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                    # params = {
                    #     'receptor': phonenumber,
                    #     'token': key,
                    #     'template': 'Verify',
                    #     'message': 'Kaveh specialized Web service '
                    # }
                    # response = api.verify_lookup(params)
                    OtpNumber.objects.create(
                        phonenumber=phonenumber, otp_number=key)
                    return Response({
                        'status': True,
                        'detail':
                            'کد تایید ارسال شد.'
                    })
            else:
                return Response({
                    'status': False,
                    'detail': 'send otp error.'
                })
    else:
        return Response({
            'status': False,
            'detail': 'شماره تلفن وارد نشده است.'
        })


def send_otp(phone):  # create otp number.
    if phone:
        key = random.randint(999, 9999)
        return key
    else:
        return False


@ api_view(['POST'])
@permission_classes([AllowAny])
def otp_validator(request):  # validation otp code With phonenumber.
    otp_number = request.POST.get('otp')
    phonenumber = request.POST.get('phonenumber')
    if otp_number and phonenumber:
        phone = OtpNumber.objects.filter(
            phonenumber=phonenumber, otp_number=otp_number)
        obj = phone.first()
        if obj and obj.otp_number == otp_number:
            obj.validate = True
            obj.save()
            return Response({
                'status': True,
                'detail': 'کاربر با موفقیت ثبت نام شد.'
            })
        else:
            return Response({
                'status': False,
                'detail': 'کد تایید منطبق نیست.'
            })
    else:
        return Response({
            'status': False,
            'detail': 'کد تایید وارد نشده است.'
        })


@ api_view(['POST'])
@permission_classes([AllowAny])
def registeration(request):  # set password and user registeration.
    password = request.POST.get('password')
    phonenumber = request.POST.get('phonenumber')
    if phonenumber and password:
        res = re.search(match_re, password)
        if res:
            myobj = OtpNumber.objects.filter(phonenumber=phonenumber)
            obj = myobj.first()
            if obj:
                if obj.validate:
                    temp_data = {
                        'phone': phonenumber,
                        'password': password,
                    }
                    serializer = CreateUserSerializer(data=temp_data)
                    serializer.is_valid(raise_exception=True)
                    user = serializer.save()
                    obj.delete()
                    if user:
                        return Response({
                            'status': True,
                            'user': UserSerializer(user).data,
                            'token': AuthToken.objects.create(user)[1],
                            'detail': 'کاربر با موفقیت ثبت نام شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail': 'اوه اوه یه مشکلی پیش اومده.'
                        })
                else:
                    return Response({
                        'status': False,
                        'detail': 'otp تایید نشده است.'
                    })
            else:
                return Response({
                    'status': False,
                    'detail': 'شماره موبایل پیدا نشد.'
                })
        else:
            return Response({
                'status': False,
                'detail': 'طول پسورد باید حداقل 8 کاراکتر باشد و شامل حداقل یک عدد و یک حرف باشد.'
            })
    else:
        return Response({
            'status': False,
            'detail': 'شماره موبایل یا رمز عبرور وارد نشده است.'
        })


class LoginView(KnoxLoginView):  # login user.
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = LoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super().post(request, format=None)


@ api_view(['POST'])
@permission_classes([AllowAny])
# send otp code to phonenumber for change password.(The user must be already registered.).
def phone_validation_passchange(request):
    phonenumber = request.POST.get('phonenumber')
    if phonenumber:
        user = User.objects.filter(phone__iexact=phonenumber)
        if user.exists():
            key = send_otp(phonenumber)
            if key:
                obj = OtpNumber.objects.filter(phonenumber=phonenumber)
                if obj:
                    objcount = obj.first()
                    if objcount.counts < 7:
                        # api = KavenegarAPI(
                        #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                        # params = {
                        #     'receptor': phonenumber,
                        #     'token': key,
                        #     'template': 'Verify',
                        #     'message': 'Kaveh specialized Web service '
                        # }
                        # response = api.verify_lookup(params)
                        objcount.counts += 1
                        objcount.otp_number = key
                        objcount.save()
                        return Response({
                            'status': True,
                            'detail':
                            'کد تایید ارسال شد.'
                        })
                    else:
                        return Response({
                            'status': False,
                            'detail':
                            'تعداد درخواست های تایید هویت پیامکی بیش از حد مجاز است لطفا با بخش پشتیبانی تماس فرمایید.'
                        })
                else:
                    # api = KavenegarAPI(
                    #     '7952507248584D75533155316553305A71497849324973554D465645566E474851547333537367396E56303D')
                    # params = {
                    #     'receptor': phonenumber,
                    #     'token': key,
                    #     'template': 'Verify',
                    #     'message': 'Kaveh specialized Web service '
                    # }

house/account/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<style>
  .nav-pills .nav-link.active,
  .nav-pills .show>.nav-link {
    color: blue !important;
    background-color: white;
  }
</style>




<div class="row">


  <div class="col-md-3" style="margin-left: 0px !important;padding-left: 0px !important;">

    <div class="p-3 m-3 text-center bg-white border" style="margin-bottom: -14px !important;">
      <img class="text-center m-1" src="{% static 'img/prof.svg' %}" alt="">
      <div class="p-2 m-1" style="font-size:14px;">{{ user.get_full_name }}</div>
      <div class="p-2 m-1 text-secondary" style="font-size:13px;">{{ user.phone }}</div>
      <div class="p-2 m-1 text-secondary" style="font-size:13px;">{{user.email}}</div>
    </div>

    <div class="nav flex-column nav-pills p-3 m-3 border bg-white" id="v-pills-tab" role="tablist"
      aria-orientation="vertical">

      <a class="nav-link p-2 m-1 text-dark active" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile"
        role="tab" aria-controls="v-pills-profile" aria-selected="false" style="font-size:13px;"><i
          class="fa fa-user ml-3" aria-hidden="true" style="font-size:15px;"></i>
        اطلاعات حساب کاربری</a>

      <a class="nav-link p-2 m-1 text-dark" id="v-pills-bookmark-tab" data-toggle="pill" href="#v-pills-bookmark"
        role="tab" aria-controls="v-pills-bookmark" aria-selected="false" style="font-size:13px;"><i
          class="fa fa-bookmark-o ml-3" style="font-size:15px;"></i>نشان شده ها</a>


      <a class="nav-link p-2 m-1 text-dark" id="v-pills-exite-tab" data-toggle="pill" href="#v-pills-exite" role="tab"
        aria-controls="v-pills-exite" aria-selected="false" style="font-size:13px;"><i class="fa fa-sign-out ml-3"
          aria-hidden="true" style="font-size:15px;"></i>
        خروج</a>



    </div>

  </div>


  <div class="col-md-9" style="margin-right: 0px !important;padding-right: 0px !important;">
    <div class="tab-content p-3 ml-3 mt-3 mb-3 border bg-white" id="v-pills-tabContent">





      <div class="tab-pane fade" id="v-pills-bookmark" role="tabpanel"
        aria-labelledby="v-pills-bookmark-tab" style="min-height: 633px;">
        <div class="container">
          <div class="p-2 mb-2 border-bottom">علاقه مندی های من</div>
          <div id="userbookmark" class="row">

          </div>
        </div>
      </div>


      <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab"
        style="min-height: 633px;">
        <div class="container">
          <div class="p-2 border-bottom mb-2">اطلاعات شخصی</div>
          <div class="row">
            <div class="col-md-6 border-left">

              <div class="border-bottom p-3">
                <div style="font-size:14px;">نام:</div>
                <div id="first_name" class="p-2 text-secondary" style="font-size:13px;"></div>
                <div id="--first_name" style="display:none;"><input id="val-first_name" class="form-control" type="text"
                    placeholder="Default input">
                  <button id="submit-first_name" type="button"
                    class="submit p-1 mt-1 mb-1 btn btn-success btn-sm btn-block" style="font-size:13px;">ثبت
                    ویرایش</button>
                </div>
                <div id="edit-first_name" class="const text-left" style="font-size:20px;"><i
                    class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i>
                </div>
                <div id="-first_name"></div>
              </div>


              <div class="border-bottom p-3">
                <div style="font-size:14px;">نام خانوادگی:</div>
                <div id="last_name" class="p-2 text-secondary" style="font-size:13px;"></div>
                <div id="--last_name" style="display:none;"><input id="val-last_name" class="form-control" type="text"
                    placeholder="Default input">
                  <button id="submit-last_name" type="button"
                    class="submit p-1 mt-1 mb-1 btn btn-success btn-sm btn-block" style="font-size:13px;">ثبت
                    ویرایش</button>
                </div>
                <div id="edit-last_name" class="const text-left" style="font-size:20px;"><i
                    class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i>
                </div>
                <div id="-last_name"></div>
              </div>


              <div class="border-bottom p-3">
                <div style="font-size:14px;">شماره تلفن همراه:</div>
                <div id="phone" class="p-2 text-secondary" style="font-size:13px;"></div>
                <div id="--phone" style="display:none;"><input id="val-phone" class="form-control" type="text"
                    placeholder="Default input">
                  <button id="submit-phone" type="button" class="submit p-1 mt-1 mb-1 btn btn-success btn-sm btn-block"
                    style="font-size:13px;">ثبت ویرایش</button>
                </div>
                <div id="edit-phone" class="const text-left" style="font-size:20px;"><i
                    class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i>
                </div>
                <div id="-phone"></div>
              </div>

            </div>

            <div class="col-md-6">

              <div class="border-bottom p-3">
                <div style="font-size:14px;">پست الکتریکی</div>
                <div id="email" class="p-2 text-secondary" style="font-size:13px;"></div>
                <div id="--email" style="display:none;"><input id="val-email" class="form-control" type="text"
                    placeholder="Default input">
                  <button id="submit-email" type="button" class="submit p-1 mt-1 mb-1 btn btn-success btn-sm btn-block"
                    style="font-size:13px;">ثبت ویرایش</button>
                </div>
                <div id="edit-email" class="const text-left" style="font-size:20px;"><i
                    class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i>
                </div>
                <div id="-email"></div>
              </div>

              <div class="p-3">
                <div style="font-size:14px;">رمز عبور</div>
                <div id="password" class="p-2 text-secondary" style="font-size:13px;"></div>
                <div id="--password" style="display:none;"><input id="val-password" class="form-control" type="text"
                    placeholder="Default input">
                  <button id="submit-password" type="button"
                    class="submit p-1 mt-1 mb-1 btn btn-success btn-sm btn-block" style="font-size:13px;">ثبت
                    ویرایش</button>
                </div>
                <div id="edit-password" class="const text-left" style="font-size:20px;"><i
                    class="fa fa-pencil-square-o text-danger" aria-hidden="true"></i>
                </div>
                <div id="-password"></div>
              </div>

            </div>
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="v-pills-exite" role="tabpanel" aria-labelledby="v-pills-exite-tab">...</div>

    </div>
  </div>



</div>



{% endblock content %}
{% block js %}
{{ block.super }}


<script>
  
    $('#first_name').html('');
    $('#last_name').html('');
    $('#phone').html('');
    $('#email').html('');
    $('#password').html('');
    $.ajax({
      url: "{% url 'account:userinfo' %}",
      type: "GET",
      headers: {
        "Authorization": "Token" + " " + window.localStorage.getItem('token'),
      },
      success: function (data) {
        if (data) {
          $('#first_name').append(data.first_name)
          $('#last_name').append(data.last_name)
          $('#phone').append(data.phone)
          $('#email').append(data.email)
          $('#password').append(data.password)
        }
      },
      error: function (jqXHR, textStatus, errorThrown) {
        console.log(textStatus, errorThrown, jqXHR);
      }
    });
  

  $(".const").click(function (event) {
    event.preventDefault();
    $("#--" + $(this).attr('id').split('-')[1]).fadeToggle();
  });
  $(".submit").click(function (event) {
    event.preventDefault();
    $.post({
      url: "http://127.0.0.1:8000/edit/",
      headers: {
        "Authorization": "Token" + " " + window.localStorage.getItem('token'),
      },
      data: {
        'key': $(this).attr('id').split('-')[1],
        'value': $('#val-' + $(this).attr('id').split('-')[1]).val(),
      },
      success: function (response) {
        console.log(response);
        if (response.status == true) {
          $("#--" + response.key).fadeOut();
          $("#" + response.key).html('').append(response.value);
          $("#-" + response.key).addClass('text-success').append('ویرایش با موفقیت انجام شد.').fadeOut(1800)
        }
      },
      error: function (jqXHR, textStatus, errorThrown) {
        console.log(textStatus, errorThrown, jqXHR);
      }
    });
  });

  $("#v-pills-bookmark-tab").click(function (event) {
    event.preventDefault();
    $('#userbookmark').html('');
    $.ajax({
      url: "{% url 'account:getuserbookmark' %}",
      type: "GET",
      headers: {
        "Authorization": "Token" + " " + window.localStorage.getItem('token'),
      },
      success: function (data) {
        if (data) {
          $.each(data, function () {
            var url = "{% url 'base:detail' 123 %}";
            var id = $(this)[0]['house']
            url = url.replace('123', id);
            html = `<div class="col-md-4">
                      <div class="border p-2 m-1 shadow p-3 mb-5 bg-white rounded" style="border-radius:5px;min-height: 289px;">
                          <div class="p-2 text-center"> 
                              <a href="${url}">
                                  <img width="220" src="${$(this)[0]['items'][0]['image']}" alt="">
                              </a>
                          </div>
                          <div class="text-dark p-2 m-1 text-center font-weight-bold" style="font-size:13px;"">${$(this)[0]['title']}</div>
                          <div class="border border-secondary p-1 m-1 text-secondary text-center">${$(this)[0]['price']}<span>تومان</span></div>
                      </div>
                  </div>`
            $('#userbookmark').append(html);
          });
        }
      },
      error: function (jqXHR, textStatus, errorThrown) {
        console.log(textStatus, errorThrown, jqXHR);
      }
    });
  });


</script>

{% endblock js %}

house/account/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}

<div class="container">
	<div class="row" style="justify-content:center;">
		<div class="col-md-6 m-5">
			<div class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">ورود با شماره تلفن
					همراه.</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">شماره تلفن همراه:</div>
					<input id="phonenumber" class="form-control form-control-lg" type="text"
						placeholder="0 9 * * * * * * * * *" style="direction:ltr;">
				</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">رمز عبور</div>
					<input id="password" class="form-control form-control-lg" type="password"
						placeholder="رمز عبور خود را وارد کنید">
				</div>
				<a href="">
					<div id="login" class="border bg-primary text-center text-white p-2 mt-2"
						style="border-radius:7px;">
						ورود
					</div>
				</a>
				<div class="text-danger" id="error" style="font-size:14px;"></div>
				<div class="p-2"><a class="text-decoration-none" href="{% url 'account:passwordrecovery_page' %}"
						style="font-size:14px;">رمز عبور خود را فراموش كرده ام.</a></div>
				<div class="p-2">
					<span style="font-size:14px;">اگر در فروشگاه حساب کاربری ندارید ثبت نام کنید.</span>
					<a class="text-decoration-none" href="{% url 'account:register_page' %}"><span
							class="border border-primary p-2" style="font-size:14px;border-radius:5px;">ایجاد حساب
							کاربری</span></a>
				</div>
			</div>
		</div>
	</div>
</div>

{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}

<script>
	$('#login').on('click', function (event) {
		event.preventDefault();
		$('#error').html('');
		$("#error").removeClass('p-2');
		$.post({
			url: "http://127.0.0.1:8000/login/",
			data: {
				'phone': $('#phonenumber').val(),
				'password': $('#password').val(),
			},
			success: function (response) {
				window.localStorage.setItem('token', response.token);
				window.location.replace("{% url 'base:homepage' %}");
			},
			error: function (jqXHR, textStatus, errorThrown) {
				console.log(textStatus, errorThrown, jqXHR);
				if (jqXHR.responseJSON.detail) {
					$('#error').append(jqXHR.responseJSON.detail);
					$("#error").addClass('p-2');
				}
			}
		});
	});
	$(".const").click(function (event) {
		event.preventDefault();
		$("#--" + $(this).attr('id').split('-')[1]).fadeToggle();
	});
	$(".submit").click(function (event) {
		event.preventDefault();
		$.post({
			url: "http://127.0.0.1:8000/edit/",
			headers: {
				"Authorization": "Token" + " " + window.localStorage.getItem('token'),
			},
			data: {
				'key': $(this).attr('id').split('-')[1],
				'value': $('#val-' + $(this).attr('id').split('-')[1]).val(),
			},
			success: function (response) {
				console.log(response);
				if (response.status == true) {
					$("#--" + response.key).fadeOut();
					$("#" + response.key).html('').append(response.value);
					$("#-" + response.key).addClass('text-success').append('ویرایش با موفقیت انجام شد.').fadeOut(1800)
				}
			},
			error: function (jqXHR, textStatus, errorThrown) {
				console.log(textStatus, errorThrown, jqXHR);
			}
		});
	});
</script>




{% endblock js %}

house/account/templates/set_password.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% block nav %}
{% endblock nav %}
<div class="container">
	<div class="row" style="justify-content:center;">
		<div class="col-md-6 m-5">
			<div class="border bg-white m-2 p-4 shadow rounded" style="border-radius:7px;">
				<div class="p-3 mb-2 bg-danger text-white" style="font-size:15px;border-radius:7px;">لطفا برای حساب کاربری خود یک رمز وارد کنید.</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">رمز عبور</div>
					<input id="password" class="form-control form-control-lg" type="password" placeholder="رمز عبور خود را وارد کنید" >
				</div>
				<div class="p-1">
					<div class="p-2" style="font-size:15px;">تکرار رمز عبور</div>
					<input id="password2" class="form-control form-control-lg" type="password" placeholder="تکرار رمز عبور خود را وارد کنید" >
				</div>
				<a href="#">
					<div id="set_password" class="border bg-primary text-center text-white p-2 mt-2" style="border-radius:7px;">
						ثبت رمز عبور
					</div>
				</a>
				<div class="text-danger" id="error" style="font-size:14px;"></div>
			</div>
		</div>
	</div>
</div>
{% block footer %}
{% endblock footer %}

{% endblock content %}
{% block js %}
{{ block.super }}
<script>
	$('#set_password').on('click', function(event) {  
		event.preventDefault();
		$('#error').html('');
		$( "#error" ).removeClass('p-2');
		if ($('#password').val() == $('#password2').val()) {
			$.post({
				url: "http://127.0.0.1:8000/user_registeration/",
				data: {
					'phonenumber':window.localStorage.getItem('userphonehistory'),
					'password':$('#password').val(),
				},
				success: function(response) {
					$('#error').html('');
					$( "#error" ).removeClass('p-2');
					if (response.status == false) {
						$('#error').append(response.detail);
						$( "#error" ).addClass('p-2');
					}
					else if(response.status == true){
						window.localStorage.removeItem('userphonehistory');
						window.localStorage.setItem('token', response.token);
						window.location.replace('{% url 'base:homepage' %}');
					}
				},
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(textStatus, errorThrown, jqXHR);
				}
			});
		}else{
			$('#error').append('رمز عبور با تکرار رمز عبور برابر نیست.');
			$( "#error" ).addClass('p-2');
		}
	});



	
</script>
{% endblock js %}