house/account/urls.py
from django.urls import path
from knox import views as knox_views
from django.contrib.auth.views import LogoutView
from django.conf.urls import url
from account.views import (register_page, phone_validation,
                           otp_validator, login_page, set_password,
                           registeration, LoginView, passwordrecovery_page,
                           change_password, phone_validation_passchange,
                           new_password_replace, dashboard_page, userinfo, edituserinfo, bookmark, bookmarkdisplay, getuserbookmark
                           )


urlpatterns = [
    path('bookmark-display/', bookmarkdisplay, name='bookmarkdisplay'),
    path('bookmark-house/', bookmark, name='bookmark'),
    path('user-bookmark/', getuserbookmark, name='getuserbookmark'),
    path('dashboard/', dashboard_page, name='dashboard_page'),
    path('userinformations/', userinfo, name='userinfo'),
    path('edit/', edituserinfo, name='edituserinfo'),
    path('new_password_replace/', new_password_replace,
         name='new_password_replace'),
    path('phone_validation_pass/', phone_validation_passchange,
         name='phone_validation_passchange'),
    path('password_change/', change_password, name='change_password'),
    path('password-recovery/', passwordrecovery_page,
         name='passwordrecovery_page'),
    path('registration/', register_page, name='register_page'),
    path('user_registeration/', registeration, name='registeration'),
    path('password/', set_password, name='set_password'),
    path('loginuser/', login_page, name='login_page'),
    path('validation_number/', phone_validation, name='phone_validation'),
    path('validation_otp/', otp_validator, name='otp_validator'),
    url(r'login/', LoginView.as_view(), name='knox_login'),
    url(r'logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('logout_user/', LogoutView.as_view(), name='logout'),
]

house/base/urls.py
from django.urls import path

from .views import homepage, Ads, detail, housedetail

urlpatterns = [
    path('', homepage, name='homepage'),
    path('getads/', Ads.as_view(), name='Ads'),
    path('housedetails/', housedetail, name='housedetail'),
    path('housedetail/<int:id>/', detail, name='detail'),
    
]

house/house/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('base.urls', 'base'), namespace='base')),
    path('', include(('account.urls', 'account'), namespace='account')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

house/base/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


def image_path(instance, filename):
    return "%s/%s" % (instance.house.id, filename)



class House(models.Model):
    TYPE1 = (
        ('A', 'آپارتمان'),
        ('B', 'خانه و ویلا'),
        ('C', 'زمین و کلنگی'),
    )
    ROOMS = (
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
    )
    
    FLOORS = (
        ('Z', 'زیر هم کف'),
        ('H', 'هم کف'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10'),
    )
    
    ADVERTISER = (
        ('A', 'املاک'),
        ('S', 'شخصی'),
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    house_type = models.CharField(max_length=1, choices=TYPE1)  
    price = models.PositiveIntegerField(null=True)
    publish_date = models.DateTimeField(auto_now_add=True, null=True)
    size = models.PositiveSmallIntegerField(null=True)
    number_of_rooms = models.CharField(max_length=2, choices=ROOMS)
    floor = models.CharField(max_length=2, choices=FLOORS)
    building_age = models.PositiveSmallIntegerField(null=True)
    status = models.BooleanField(default=False)
    just_urgent = models.BooleanField(default=False)
    Advertiser = models.CharField(max_length=1, null=True, choices=ADVERTISER)
    
class HouseImage(models.Model):
    house = models.ForeignKey(House, related_name='items', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_path, null=True)
    def __str__(self):
        return self.house.title
    
class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    house = models.ForeignKey(House, on_delete=models.CASCADE, null=True)
    

house/base/views.py
from django.shortcuts import render
from .serializers import house_serializer
from rest_framework.permissions import AllowAny
from .models import House
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework import status
from rest_framework.generics import ListAPIView
from django_filters.rest_framework import DjangoFilterBackend


def homepage(request):
    return render(request, 'home.html')

@permission_classes([AllowAny])
def detail(request, id):
    ctx = {}
    obj = House.objects.get(id=id)
    ctx['house_id'] = obj.id
    return render(request, 'detail.html', ctx)



class Ads(ListAPIView):
    serializer_class = house_serializer
    permission_classes = [AllowAny]
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['size', 'price', 'building_age','number_of_rooms','Advertiser', 'floor']

    def get_queryset(self):
        size1 = self.request.GET.get('size1')
        size2 = self.request.GET.get('size2')
        price1 = self.request.GET.get('price1')
        price2 = self.request.GET.get('price2')
        building_age1 = self.request.GET.get('building_age1')
        building_age2 = self.request.GET.get('building_age2')
        number_of_rooms = self.request.GET.get('number_of_rooms')
        Advertiser = self.request.GET.get('Advertiser')
        floor = self.request.GET.get('floor')
        if price1 and price2:
            return House.objects.filter(price__gte=price1, price__lte=price2)
        elif size1 and size2:
            return House.objects.filter(size__gte=size1, size__lte=size2)
        elif building_age1 or building_age2:
            return House.objects.filter(building_age__gte=building_age1, building_age__lte=building_age2)
        elif number_of_rooms:
            return House.objects.filter(number_of_rooms=number_of_rooms)
        elif Advertiser:
            return House.objects.filter(Advertiser=Advertiser)
        elif floor:
            return House.objects.filter(floor=floor)        
        else:
            return House.objects.all()
        
        
        
        
        # def get_queryset(self):
        # order = self.request.GET.get('order')    
        # size1 = self.request.GET.get('size1')
        # size2 = self.request.GET.get('size2')
        # price1 = self.request.GET.get('price1')
        # price2 = self.request.GET.get('price2')
        # building_age1 = self.request.GET.get('building_age1')
        # building_age2 = self.request.GET.get('building_age2')
        # number_of_rooms = self.request.GET.get('number_of_rooms')
        # Advertiser = self.request.GET.get('Advertiser')
        # floor = self.request.GET.get('floor')
        # if price1 and price2:
        #     return House.objects.filter(price__gte=price1, price__lte=price2).order_by('order')
        # elif size1 and size2:
        #     return House.objects.filter(size__gte=size1, size__lte=size2).order_by('order')
        # elif building_age1 or building_age2:
        #     return House.objects.filter(building_age__gte=building_age1, building_age__lte=building_age2).order_by('order')
        # elif number_of_rooms:
        #     return House.objects.filter(number_of_rooms=number_of_rooms).order_by('order')
        # elif Advertiser:
        #     return House.objects.filter(Advertiser=Advertiser).order_by('order')
        # elif floor:
        #     return House.objects.filter(floor=floor).order_by('order')        
        # else:
        #     return House.objects.all().order_by('order')



@ api_view(['GET'])
@permission_classes([AllowAny])
def housedetail(request):
    obj_id = request.GET.get('id')
    if obj_id and obj_id.isdigit():
        obj = House.objects.get(id=obj_id)
        serializer = house_serializer(obj)
        return Response(serializer.data, status=status.HTTP_200_OK)
    return Response(status=status.HTTP_400_BAD_REQUEST)

house/base/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <title>House</title>
</head>

<body>

  {% block nav %}

  <nav class="navbar navbar-expand-lg navbar-light bg-white m-2">
    <a class="navbar-brand" href="{% url 'base:homepage' %}"><img width="70" src="{% static 'img/32.png' %}" alt=""></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white btn btn-primary m-1" href="{% url 'base:homepage' %}"><i class="fa fa-home ml-1"></i>خانه</a>
        </li>
        {% if request.user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link text-white btn btn-primary m-1" href="{% url 'account:dashboard_page' %}">پنل کاربری</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link text-white btn btn-primary m-1" href="{% url 'account:login_page' %}">ورود کاربر</a>
        </li>
        {% endif %} 
      </ul>
    </div>
  </nav>
  {% endblock nav %}

  {% block content %}{% endblock content %}
















  {% block footer %}
  

  <div class="footer mt-3 border-top" style="background-color: white;">
    <div class="container">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-3 text-center p-2 mt-5">
            <!-- <p>تلفن تماس: 6415</p>
            <p>ادرس: ستارخان جنب پمپ بنزین ...</p> -->
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">بازگشن کالا</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">سوالات متداول</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">فرصت های شغلی</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">راهنمای خرید</a></div>
          </div>
          <div class="col-md-3 text-center p-2 mt-5">
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">مرکز پشتیبانی: 6415</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">دفتر مرکزی: تهران-ستارخان-
                شهراارا...</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">فرصت های شغلی</a></div>
            <div class="p-2" style="font-size: 14px;"><a class="text-secondary" href="">ساعات کاری: از شنبه الی چهارشنبه
                از ساعت8.00 الی 16.00</a></div>
          </div>
          <div class="col-md-3 text-center p-2">
            <h4 class="text-center">STORE</h4>
            <p class="text-secondary">فروشگاه store از سال 1376 شروع به کار کرده و خیلی بد کار کرده و الان تازه داره
              درست میشه</p>
          </div>
          <div class="col-md-3 text-center p-2 mt-5">
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>
            <a href="#" class="fa fa-facebook social p-2 text-white mt-2"></a>
            <a href="#" class="fa fa-twitter social p-2 text-white mt-2" style="background-color: #55ACEE;"></a>
            <a href="#" class="fa fa-youtube social p-2 text-white mt-2" style="background-color: #bb0000;"></a>
            <a href="#" class="fa fa-instagram social p-2 text-white mt-2" style="background-color: #C12B2B;"></a>

          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock footer %}






  {% block js %}
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/5a32a1eab1.js"></script>
  <script>



  </script>

  {% endblock js %}
</body>

</html>

house/base/templates/detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="border bg-white">
                <div class="p-1">
                    <img id="primary_image" src="" class="w-100 p-2 border-bottom" alt="">
                </div>
                <div id="images" class="row pr-4 pl-3 pt-1 pb-2">
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="border bg-white">
                <div id="title" class="m-2 p-2 border-bottom"></div>
                <div class="m-2 p-2">
                    <button type="button" class="btn btn-danger phonedisplay">اطلاعات تماس</button>
                    <span class="border border-danger p-2 mr-3 text-danger" style="display: none;" id="phone">{{ user.phone }}</span>
                    <div class="border-bottom p-2 mt-3">
                        <div class="d-inline pr-5">اگهی دهنده</div>
                        <div id="advetiser" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">دسته بندی</div>
                        <div id="category" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">محله</div>
                        <div id="location" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">متراژ</div>
                        <div id="size" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">سن بنا</div>
                        <div id="biuliding_age" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">تعداد اوتاق</div>
                        <div id="number_room" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="border-bottom p-2">
                        <div class="d-inline pr-5">قیمت</div>
                        <div id="price" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="p-2">
                        <div class="d-inline pr-5">طبقه</div>
                        <div id="floor" class="d-inline pl-5" style="float:left;"></div>
                    </div>
                    <div class="text-left mt-5">
                        <button id="share" type="button" data-content="کپی شد" data-placement="top" class="btn btn-outline-primary"><i
                                class="fa fa-share-alt text-center"></i></button>
                        <button id="bookmark" type="button" class="btn btn-outline-primary"><i class="fa fa-bookmark-o"
                                id="book"></i></button>
                    </div>

                </div>

            </div>
        </div>

    </div>
</div>




{% endblock content %}
{% block js %}
{{ block.super }}


<script>
    bookmarkdisplay()
    $.ajax({
        url: "{% url 'base:housedetail' %}?id={{house_id}}",
        type: "GET",
        success: function (data) {
            if (data) {
                $('#title').append(data.title);
                $('#advetiser').append(data.Advertiser);
                $('#category').append(data.house_type);
                $('#location').append();
                $('#size').append(data.size);
                $('#biuliding_age').append(data.building_age);
                $('#number_room').append(data.number_of_rooms);
                $('#price').append(data.price);
                $('#floor').append(data.floor);
                $('#primary_image').attr('src', data.items[0].image);

                $.each(data.items, function () {
                    html = `
                    <img id="${$(this)[0]['id']}" src="${$(this)[0]['image']}" class="p-2 m-1 img-thumbnail const img-${$(this)[0]['id']}" alt="" style="width: 30%;">`
                    $('#images').append(html);
                });
                $(".const").click(function () {
                    $(".const").removeClass('imgborder');
                    $(".img-" + $(this).attr('id')).addClass('imgborder');
                    $('#primary_image').attr('src', $(".img-" + $(this).attr('id')).attr('src'));
                    $(".img-" + $(this).attr('id')).attr('src', $('#primary_image').attr('src'));
                });
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(jqXHR);
            console.log(textStatus);
            console.log(errorThrown);
        }
    });
    function bookmarkdisplay() {
        $.post({
            url: "{% url 'account:bookmarkdisplay' %}",
            data: {
                "id": {{ house_id }},
            },
    headers: {
        "Authorization": "Token" + " " + window.localStorage.getItem('token'),
            },
    success: function (response) {
        if (response.status == true) {
            $('#book').removeClass('fa-bookmark-o').addClass('fa-bookmark text-primary');
        }
        else {
            $('#book').removeClass('fa-bookmark text-primary').addClass('fa-bookmark-o');
        }
    },
    error: function (jqXHR, textStatus, errorThrown) {
        console.log(textStatus, errorThrown, jqXHR);
    }
        });
    }
    $('#bookmark').on('click', function (event) {
        event.preventDefault();
        $.post({
            url: "{% url 'account:bookmark' %}",
            data: {
                "id": {{ house_id }},
            },
        headers: {
        "Authorization": "Token" + " " + window.localStorage.getItem('token'),
    },
        success: function (response) {
            if (response.status == true) {
                bookmarkdisplay()
            }
        },
        error: function (jqXHR, textStatus, errorThrown) {
            console.log(textStatus, errorThrown, jqXHR);
        }
        });
    });
    $('#share').on('click', function (event) {
        event.preventDefault();
        var url = window.location.href;
        var urls = document.createElement("input");
        urls.setAttribute("value", url);
        document.body.appendChild(urls);
        urls.select();
        document.execCommand("copy");
        document.body.removeChild(urls);
        $('#share').popover('show');
        setTimeout(function () {
            $('#share').popover('hide');
        }, 1000);
    });
    $(".phonedisplay").click(function(event){
        event.preventDefault();
    $("#phone").fadeToggle();
  });

</script>

{% endblock js %}